### ISSUE TITLE
SVG images not scaling properly in IE & Edge

### ISSUE THREAD

**Issue by TeddMcAdams** [opencollective/frontend#159]
![screenshot 2017-12-17 02 25 03](https://user-images.githubusercontent.com/15876990/34077540-89b5157e-e2d4-11e7-9e41-8dcf8c31a4e5.png)

Issue can be seen by viewing https://reactiveui.net/ in Microsoft IE or Edge

In Edge, the SVG icons scale infinitely, filling the entire view area.
In IE, the SVG icons have infinite width, causing them to be in their own row.

I believe this issue can be resolved by adding the width attribute to the SVG.
Attaching a PR.  New to GitHub so please let me know if I'm doing something incorrectly.  :)

**Comment by xdamman** [comment]
Thanks for fixing this!

Happy holidays!
