### ISSUE TITLE
favicon broken

### ISSUE THREAD

**Issue by bradvogel** [opencollective/frontend#199]
Just noticed that your favicon is broken:
![image](https://user-images.githubusercontent.com/821706/34854776-908add18-f6f0-11e7-90b4-8491ff240eb4.png)

**Comment by piamancini** [comment]
@bradvogel it's loading fine for me on chrome. what browser are you using?

**Comment by bradvogel** [comment]
Chrome 63. The URL https://opencollective.com/favicon.ico returns a 404 for me. I also don't see the (alternative) favicon &lt;link> tag in the page's source.
