### ISSUE TITLE
Icons seem to be placed incorrectly

### ISSUE THREAD

**Issue by janpieterz** [opencollective/frontend#210]
See below image. The icons of the companies seem to be placed on a different card.

![image](https://user-images.githubusercontent.com/383634/35028862-63b69c98-fb58-11e7-8019-0c898d3d6be9.png)

**Comment by piamancini** [comment]
what's the url?

**Comment by janpieterz** [comment]
https://opencollective.com/babel?referral=11936 is where I get it (both in logged in and private session).

**Comment by piamancini** [comment]
hmmm loads fine for me. Weird. can you try on a different browser?

<img width="915" alt="screen shot 2018-01-17 at 12 52 20 pm" src="https://user-images.githubusercontent.com/3671070/35052018-54595e20-fb85-11e7-8552-fb3e7e6e61ad.png">

**Comment by janpieterz** [comment]
Chrome loads fine, Firefox fails, Edge fails, Internet Explorer *cough* fails

**Comment by piamancini** [comment]
hmm safari fails as well. 
ok we'll file it as a bug.

**Comment by asood123** [comment]
Weird, I can repro it in firefox. Will look this week.

**Comment by piamancini** [comment]
@asood123 status?

**Comment by asood123** [comment]
No update. Couldn't find an obvious fix. Have a theory on why it might be
happening, will test this friday.

**Comment by asood123** [comment]
Theory failed. Still happening in production and I can't repro it locally on any browser. Open to ideas... Happens on same two spots (and is now happening between Domainr and MaxFlow BVBA, instead of Domainr and Intreba).

**Comment by znarf** [comment]
Fixed by @asood123.
