### ISSUE TITLE
Sign Up: Both Email and Password

### ISSUE THREAD

**Issue by coooolers** [opencollective/frontend#228]
Hi

Looks like the system asks for Email only during the Sign Up. In this scenario, a user needs to open her Email Inbox and click on the Login link every time she wants to visit the website.

If I am right, can you add/store the Password field in the db itself and let the user simply remember it.

Thanks

**Comment by clarete** [comment]
We chose to not store passwords in our database and require the user to open the link in their email address. Users would have to do that either way to verify their email addresses.

And after the user login once, the application stores an authentication token in the browser (`localStorage`) so the user doesn't have to open their email app every single time they wanted to log in.

Thank you!
