### ISSUE TITLE
[UX] Color and hover color of URL

### ISSUE THREAD

**Issue by pierreneter** [opencollective/frontend#277]
It's still nice at content of article or description of projects.

![hover](https://user-images.githubusercontent.com/12815768/37068598-176cd6d0-21e2-11e8-96c4-53978fda4f4e.png)
_(https://opencollective.com/wwcodetwincities)_

But, at the banner, it's a bad case.

![hover2](https://user-images.githubusercontent.com/12815768/37068945-cde50a4e-21e3-11e8-85b9-300f05eef54f.png)

hover:

![hover3](https://user-images.githubusercontent.com/12815768/37068959-d95bdf10-21e3-11e8-8e8c-19d3725b69f6.png)
_(https://opencollective.com/pierreneter)_

**Comment by piamancini** [comment]
thanks @pierreneter will add it to bug fix day this friday
