### ISSUE TITLE
Grammatically incorrect ui regarding contributor counts

### ISSUE THREAD

**Issue by welkie** [opencollective/frontend#309]
Just a nit pick here, but even when there are no sponsors at all, it displays "organizations and x people are supporting us."

See screenshot for example:

Open collective ui bug https://imgur.com/gallery/uzbdP

**Comment by welkie** [comment]
Looks like it happens in reverse too with just sponsors and no individual contributors:

Open collective UI bug 2 https://imgur.com/gallery/9IwxW

**Comment by znarf** [comment]
@welkie Thank you for your report, that should be fixed there:
https://github.com/opencollective/opencollective-api/pull/1237
