### ISSUE TITLE
Unable to update payment method 

### ISSUE THREAD

**Issue by johnmetta** [opencollective/frontend#327]
Subscriptions page->Update payment method:

<img width="547" alt="screen shot 2018-04-19 at 8 25 13 pm" src="https://user-images.githubusercontent.com/340268/39029278-d978d162-440f-11e8-93ca-8ed512bf394f.png">

Choose another payment method, "Save" button becomes active. Clicking save button throws `Uncaught (in promise) TypeError: this.update is not a function` in `subscriptions.js`:

<img width="807" alt="screen shot 2018-04-19 at 8 18 39 pm" src="https://user-images.githubusercontent.com/340268/39029330-0d299654-4410-11e8-8c66-30672cf228d6.png">

**Comment by znarf** [comment]
Fixed in: https://github.com/opencollective/frontend/pull/328/commits/8c84c930ef91b3d9b012cf0e87bae661ea11d8a2

Merged in: https://github.com/opencollective/frontend/pull/328
