### ISSUE TITLE
Duplicate Section title

### ISSUE THREAD

**Issue by znarf** [opencollective/frontend#466]
https://opencollective.com/sustainoss/events/sustainuk-2018-442ev#budget

![screen shot 2018-05-30 at 15 42 27](https://user-images.githubusercontent.com/806/40723888-206abc86-6420-11e8-8ee5-18bcd574ff9d.png)

**Comment by piamancini** [comment]
good catch @znarf

**Comment by xdamman** [comment]
Fixed in https://github.com/opencollective/frontend/pull/555
