### ISSUE TITLE
GraphQL errors in docker environment

### ISSUE THREAD

**Issue by patcon** [opencollective/frontend#467]
Hi there! I'm attempting to use the docker container development environment so that I can set up a demo of how OpenCollective can be used to support a local community.

I'm currently running into a few errors. I mitigated one with https://github.com/opencollective/opencollective-api/pull/1311, but I'm now running into a GraphQL error  when I visit a collective page.

## Screenshot

![screenshot of collective page with graphql error](https://i.imgur.com/muVYmdN.png)

## Logs

```
frontend_1  | info: GET /opensource 200 61ms
frontend_1  | error: >>> Error calling API http://localhost:13060/graphql?api_key=dvl-1510egmf4a23d80342403fb599qd {"meta":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":13060}}
frontend_1  | info: POST /api/graphql 500 12ms
```

Any thoughts? Thanks again!

**Comment by patcon** [comment]
Got it sorted: The `INTERNAL_API_URL` envvar must be added and set to http://api:3060 so that the frontend server can find it:

https://github.com/opencollective/opencollective-api/blob/master/docker/docker-compose.yml#L32
https://github.com/opencollective/frontend/blob/master/src/lib/utils.js#L211

Also, as it turns out, the database dump has some old image sources in it, that the frontend fails on when it finds (this only affects the sample `opensource` collective in the sample dev database, but `apex` works fine)

For example, this image doesn't exist anymore, but is in the dump:
https://images.githubusercontent.com/farhd

Any thoughts on how to improve this second hitch?

**Comment by znarf** [comment]
@patcon maybe the database dumps needs to be refreshed. Moving the discussion to: https://github.com/opencollective/opencollective-api/issues/1314
