### ISSUE TITLE
Stop Base64 encoding SVGs

### ISSUE THREAD

**Issue by XhmikosR** [opencollective/frontend#524]
It results in much bigger files.

**Comment by znarf** [comment]
@XhmikosR Thank you for the report!

Can you provide an example? And give a short guidance on how to assess there is base64 encoding in the example?

**Comment by XhmikosR** [comment]
@znarf I just noticed these issues in the OC PR created for BootstrapCDN. And looking at this repo's code, you can clearly see there's base64 used in some cases.

https://github.com/opencollective/frontend/search?q=base64&unscoped_q=base64

I'm not familiar with the codebase, hence why I don't submit a PR and just made an issue :)

**Comment by znarf** [comment]
Can you provide the URL of the BootstrapCDN SVG containing base64? Just to be sure we're looking at the same thing.

I think in some cases, base64 is used to embed avatars in the SVGs. That sounds ok, and I can't think of a better alternative.

**Comment by XhmikosR** [comment]
I would swear I saw whole SVG files being base64 encoded but now I can't find it. I'm gonna close this for now and if I find any I will comment here.
