### ISSUE TITLE
BootstrapCDN not working "graphql error"

### ISSUE THREAD

**Issue by welkie** [opencollective/frontend#539]
Just went to visit them from the marketing email I got. Looks like this:

![](https://i.imgur.com/Q3G426u.png)

**Comment by piamancini** [comment]
oh, it's because they updated their url after I draft it. damn. I missed it
It's opencollective.com/getbootstrapcdn now. 
I'll fix it in medium

**Comment by piamancini** [comment]
thanks for the alert Matt
