### ISSUE TITLE
Wrong translation values for 'Member Collectives' titles

### ISSUE THREAD

**Issue by hichamelkaddioui** [opencollective/frontend#643]
It looks like the translation values of `collective.collective.memberOf.collective.parent.title` is set to the template for the subtitle for non-English languages, and not the actual translation of "Member collectives".

See the [English translation](https://github.com/opencollective/frontend/blob/8533b8f8d521e890394a516c06a0417a84829179/src/lang/en.json#L131) vs [French translation](https://github.com/opencollective/frontend/blob/8533b8f8d521e890394a516c06a0417a84829179/src/lang/fr.json#L131).

**Comment by znarf** [comment]
@hichamelkaddioui you're absolutely right. I prepared a PR with that change.

https://github.com/opencollective/frontend/pull/646

Do you see anything else worth fixing?

**Comment by hichamelkaddioui** [comment]
@znarf French translation also differs:

- [on line 204](https://github.com/opencollective/frontend/blob/master/src/lang/fr.json#L204) ([en](https://github.com/opencollective/frontend/blob/master/src/lang/en.json#L204))
- [on line 547](https://github.com/opencollective/frontend/blob/master/src/lang/fr.json#L547) ([en](https://github.com/opencollective/frontend/blob/master/src/lang/en.json#L547))

I'm not sure those are really bugs, but it may be desirable translations carry the same message?

**Comment by znarf** [comment]
@hichamelkaddioui thank you, fixed these too in the PR.
